
import { Question } from './types';

export const QUIZ_DATA: Question[] = [
  {
    id: 1,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "My sister is good at cooking, but she isn't very keen on ______ the dishes.",
    options: { A: 'wash', B: 'to wash', C: 'washing', D: 'washes' },
    answer: 'C',
  },
  {
    id: 2,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "If my parents had enough money, they ______ a new house in the city center.",
    options: { A: 'will buy', B: 'would buy', C: 'would have bought', D: 'bought' },
    answer: 'B',
  },
  {
    id: 3,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "Despite the bad weather, they decided ______ for a picnic.",
    options: { A: 'go', B: 'to go', C: 'going', D: 'went' },
    answer: 'B',
  },
  {
    id: 4,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "The air in the countryside is much ______ than that in the city.",
    options: { A: 'fresh', B: 'fresher', C: 'more fresh', D: 'the freshest' },
    answer: 'B',
  },
  {
    id: 5,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "Mai asked me ______ a new dress for the party.",
    options: { A: 'if I bought', B: 'if I had bought', C: 'whether did I buy', D: 'whether I buy' },
    answer: 'B',
  },
  {
    id: 6,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "We should turn ______ all the lights before leaving the room to save electricity.",
    options: { A: 'up', B: 'on', C: 'off', D: 'into' },
    answer: 'C',
  },
  {
    id: 7,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "______ it was raining heavily, we still went to the concert.",
    options: { A: 'Although', B: 'Because', C: 'Despite', D: 'Because of' },
    answer: 'A',
  },
  {
    id: 8,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "The new library, ______ was built last year, has thousands of books.",
    options: { A: 'where', B: 'who', C: 'which', D: 'whose' },
    answer: 'C',
  },
  {
    id: 9,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "Tom used to ______ football when he was a small boy.",
    options: { A: 'play', B: 'playing', C: 'to play', D: 'played' },
    answer: 'A',
  },
  {
    id: 10,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "A: I'm really tired. B: Why don't you ______ a break?",
    options: { A: 'take', B: 'do', C: 'make', D: 'have' },
    answer: 'A',
  },
  {
    id: 11,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "My brother suggested ______ to the beach this weekend.",
    options: { A: 'go', B: 'to go', C: 'going', D: 'went' },
    answer: 'C',
  },
  {
    id: 12,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "The students were punished because they didn't ______ the teacher's instructions.",
    options: { A: 'follow', B: 'following', C: 'followed', D: 'to follow' },
    answer: 'A',
  },
  {
    id: 13,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "I have been working for this company ______ ten years.",
    options: { A: 'since', B: 'for', C: 'in', D: 'on' },
    answer: 'B',
  },
  {
    id: 14,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "We are looking forward to ______ from you soon.",
    options: { A: 'hear', B: 'hearing', C: 'to hear', D: 'heard' },
    answer: 'B',
  },
  {
    id: 15,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "The Ao Dai is the traditional ______ of Vietnamese women.",
    options: { A: 'clothes', B: 'clothing', C: 'dress', D: 'costume' },
    answer: 'C',
  },
  {
    id: 16,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "If she ______ harder, she will pass the exam.",
    options: { A: 'study', B: 'studied', C: 'studies', D: 'study' },
    answer: 'C',
  },
  {
    id: 17,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "The children are playing happily in ______ park near my house.",
    options: { A: 'a', B: 'an', C: 'the', D: '(no article)' },
    answer: 'C',
  },
  {
    id: 18,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "His parents were very ______ of his success in the competition.",
    options: { A: 'proud', B: 'pleased', C: 'happy', D: 'great' },
    answer: 'A',
  },
  {
    id: 19,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "This area is quite safe. There is ______ crime here.",
    options: { A: 'a little', B: 'much', C: 'a few', D: 'little' },
    answer: 'D',
  },
  {
    id: 20,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "You should avoid ______ too much time on social media.",
    options: { A: 'spend', B: 'to spend', C: 'spending', D: 'spent' },
    answer: 'C',
  },
  {
    id: 21,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "The novel ______ by a famous writer is very popular.",
    options: { A: 'writes', B: 'written', C: 'writing', D: 'was written' },
    answer: 'B',
  },
  {
    id: 22,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "She wishes she ______ enough money to buy that laptop.",
    options: { A: 'has', B: 'have', C: 'had', D: 'would have' },
    answer: 'C',
  },
  {
    id: 23,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "People who live in the city usually find it difficult to ______ the noise and air pollution.",
    options: { A: 'used to', B: 'use to', C: 'get used to', D: 'be used to' },
    answer: 'C',
  },
  {
    id: 24,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "The police asked him ______ he was doing at the time of the accident.",
    options: { A: 'what', B: 'who', C: 'whose', D: 'which' },
    answer: 'A',
  },
  {
    id: 25,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "We have so ______ time left to complete the project, so we need to hurry up.",
    options: { A: 'few', B: 'little', C: 'many', D: 'much' },
    answer: 'B',
  },
  {
    id: 26,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "The recycling program encourages people to ______ plastic bottles and paper.",
    options: { A: 'pick up', B: 'look up', C: 'take off', D: 'put on' },
    answer: 'A',
  },
  {
    id: 27,
    section: 'Ngữ Pháp và Từ Vựng',
    question: "A: Would you like some tea? B: No, thanks. I don't have ______ left.",
    options: { A: 'any', B: 'much', C: 'some', D: 'no' },
    answer: 'A',
  },
  {
    id: 28,
    section: 'Phát Âm',
    question: "Chọn từ có phần gạch chân được phát âm khác với ba từ còn lại: c<u>o</u>ffee, l<u>o</u>cal, h<u>o</u>bby, st<u>o</u>p",
    options: { A: 'coffee', B: 'local', C: 'hobby', D: 'stop' },
    answer: 'B',
  },
  {
    id: 29,
    section: 'Phát Âm',
    question: "Chọn từ có phần gạch chân được phát âm khác với ba từ còn lại: decid<u>ed</u>, want<u>ed</u>, stopp<u>ed</u>, need<u>ed</u>",
    options: { A: 'decided', B: 'wanted', C: 'stopped', D: 'needed' },
    answer: 'C',
  },
  {
    id: 30,
    section: 'Phát Âm',
    question: "Chọn từ có phần gạch chân được phát âm khác với ba từ còn lại: <u>th</u>ink, <u>th</u>em, <u>th</u>rough, <u>th</u>anks",
    options: { A: 'think', B: 'them', C: 'through', D: 'thanks' },
    answer: 'B',
  },
];
